---The generic host's configuration schema, as LuaCATS annotations.
---
---A deployment's `*.host.lua` file returns one `diluvium.HostConfig` table.
---These annotations never run: they exist so lua-language-server can complete
---keys and catch typos in the editor, ahead of the host's own refusal --
---which is stricter, because the host also refuses at runtime what an editor
---only warns about. The file is evaluated in an EMPTY environment, so it can
---declare and cannot compute: no `os`, no `require`, not even `tostring`.
---One file, one context: this file's context is the HOST, and guest programs
---(the `supervisor`, anything it spawns) are ordinary `.lua` in their own
---files, never inlined here.
---
---Usage, at the top of a deployment file:
---
---  ---@type diluvium.HostConfig
---  return {
---    supervisor = "supervisor.lua",
---    caps = { "lifecycle", "queue:*", "host:time" },
---    connectors = { time = true },
---  }

---@class diluvium.HostConfig
---@field supervisor string           # the root program's file; required
---@field max_instances integer?      # swarm table bound (default 64)
---@field spawns_per_step integer?    # 9.5's lifecycle rate limit (default 4)
---@field identity string?            # stamps snapshots; omit for unstamped
---@field hibernation ("on"|"off")?   # policy, not capability (default "on")
---@field caps string[]?              # the root's ceiling; children attenuate
---@field budget diluvium.HostBudget? # the root's; 0/omitted means none
---@field connectors diluvium.HostConnectors?  # everything absent is OFF

---@class diluvium.HostBudget
---@field instructions integer?      # lifetime VM instructions, not per-step
---@field memory_kb integer?

---Connectors are all off by default; naming one wires it. Which *calls* a
---program may make is still the capability grammar's question ("host:time",
---"host:sql/query", attenuating through spawns like everything else) -- a
---wired connector answers only programs that hold the grant.
---@class diluvium.HostConnectors
---@field time boolean?                        # wall-clock ms via {call="time"}
---@field listen (diluvium.HostListen|diluvium.HostListen[])?  # inbound HTTP
---@field sql diluvium.HostSql?                # SQLite, host-side
---@field crypto diluvium.HostCrypto?          # random/hash/hmac/JWT, host-side

---A listener, or an array of them. A v1 host binds at startup and never at
---runtime, so a deployment that will want several ports pre-binds the block
---here -- `listen = { {port=8080}, {port=8081} }` -- rather than binding one
---later. Up to 8. Ports must differ; queue names need not (all ports feeding
---one supervisor loop is the common case, and `conn` stays unique across
---them). A single block is still just `listen = { port = 8080 }`.
---@class diluvium.HostListen
---@field port integer                # required; 1..65535, unique per host
---@field bind string?                # IPv4 literal (default "127.0.0.1")
---@field queue string?               # requests land here, on the root
---                                   # (default "http_in"): {conn, method,
---                                   # path, body}
---@field reply_queue string?         # responses drain from here (default
---                                   # "http_out"): {conn, status, body,
---                                   # content_type?}
---@field max_body integer?           # refuse bigger bodies (default 65536)
---@field deadline_ms integer?        # per-connection; the host's own timeout
---                                   # logic (default 10000)
---@field max_conns integer?          # table bound (default 64)

---The sql connector grants a *scope*: a directory the deployment's programs
---open databases within (`host.sql.open("name")` guest-side; `args.db` on
---the wire). Which database is the program's business, so it is not named
---here; a name that resolves outside the scope is denied. Every option but
---`scope` is omittable with a safe default, and nothing is preallocated --
---a database opens when a program first names it.
---@class diluvium.HostSql
---@field scope string                # the granted directory; required, must
---                                   # exist
---@field access ("read"|"readwrite")?  # the grant (default "read"); "read"
---                                   # opens files read-only and leaves
---                                   # sql/exec unwired
---@field create boolean?             # may a named database be created?
---                                   # needs access "readwrite", and
---                                   # defaults to it
---@field max_result_rows integer?    # per-QUERY result cap; past it the
---                                   # result REFUSES, never truncates
---                                   # (default 1024)

---The crypto connector answers host:crypto/random, /hash, /hmac, /jwt_sign
---and /jwt_verify. The signing key never leaves the host: exactly one of
---key_file (the deployment shape), key_env, or key (inline, for dev) names
---it, and it must be at least 16 bytes. jwt_sign owns iat and exp -- a guest
---cannot forge a longer expiry -- and jwt_verify fixes the algorithm to
---HS256, so an "alg":"none" token is just an invalid one.
---@class diluvium.HostCrypto
---@field key string?                 # inline key (dev only); >= 16 bytes
---@field key_env string?             # name of an env var holding the key
---@field key_file string?            # path to a file holding the key
---@field default_ttl integer?        # jwt_sign ttl when a call omits it
---                                   # (seconds; default 3600)
