---The generic host's configuration schema, as LuaCATS annotations.
---
---A deployment's `*.host.lua` file returns one `diluvium.HostConfig` table.
---These annotations never run: they exist so lua-language-server can complete
---keys and catch typos in the editor, ahead of the host's own refusal --
---which is stricter, because the host also refuses at runtime what an editor
---only warns about. The file is evaluated in an EMPTY environment, so it can
---declare and cannot compute: no `os`, no `require`, not even `tostring`.
---One file, one context: this file's context is the HOST, and guest programs
---(the `supervisor`, anything it spawns) are ordinary `.lua` in their own
---files, never inlined here.
---
---Usage, at the top of a deployment file:
---
---  ---@type diluvium.HostConfig
---  return {
---    supervisor = "supervisor.lua",
---    caps = { "lifecycle", "queue:*", "host:time" },
---    connectors = { time = true },
---  }

---@class diluvium.HostConfig
---@field supervisor string           # the root program's file; required
---@field max_instances integer?      # swarm table bound (default 64)
---@field spawns_per_step integer?    # 9.5's lifecycle rate limit (default 4)
---@field identity string?            # stamps snapshots; omit for unstamped
---@field hibernation ("on"|"off")?   # policy, not capability (default "on")
---@field caps string[]?              # the root's ceiling; children attenuate
---@field budget diluvium.HostBudget? # the root's; 0/omitted means none
---@field connectors diluvium.HostConnectors?  # everything absent is OFF
---@field plugins table<string, diluvium.HostPlugin>?  # capabilities that
---                                       # live in another program
---@field visibility ("public"|"private"|"hidden")?  # what `capabilities/list`
---                                       # tells a caller EXISTS, which is not
---                                       # what it may DO (default "public")

---A plugin: a capability answered by a separate program, over a framed
---msgpack channel it inherits as fd 3. The deployment names it and points at
---its manifest; the manifest -- a self-contained `<name>.plugin.json` --
---says what the program is and what it answers. The split is the point: the
---manifest travels with the plugin and is its author's document, this block
---is the operator's and says which plugins THIS deployment wires and how
---hard it will lean on them.
---
---The table key becomes the first segment of every call the plugin answers,
---so `plugins = { rest = ... }` answers `rest/get`, gated by `host:rest/get`
---like every other hostcall. Unlike `exec`, a plugin call does not stall the
---host: it is deferred and the swarm keeps running.
---@class diluvium.HostPlugin
---@field manifest string             # required; resolved against THIS file's
---                                   # directory, not the host's cwd
---@field max_inflight integer?       # requests written before waiting for a
---                                   # reply (default: the manifest's, or 4).
---                                   # Lowering it here is the operator
---                                   # throttling a plugin they did not write
---@field call_timeout_ms integer?    # host-side backstop per call (default
---                                   # 30000). A plugin that never answers
---                                   # has its call reclaimed at this moment,
---                                   # so a guest gets a sentence not a hang
---@field visibility ("public"|"private"|"hidden"|"inherit")?  # whether
---                                   # `capabilities/list` reports this
---                                   # plugin. "public" (the default via
---                                   # inherit) lists it to every caller with
---                                   # granted=true/false beside it;
---                                   # "private" lists it only to callers
---                                   # that hold it; "hidden" never lists it,
---                                   # though a holder can still call it

---@class diluvium.HostBudget
---@field instructions integer?      # lifetime VM instructions, not per-step
---@field memory_kb integer?

---Connectors are all off by default; naming one wires it. Which *calls* a
---program may make is still the capability grammar's question ("host:time",
---"host:sql/query", attenuating through spawns like everything else) -- a
---wired connector answers only programs that hold the grant.
---@class diluvium.HostConnectors
---@field time boolean?                        # wall-clock ms via {call="time"}
---@field listen (diluvium.HostListen|diluvium.HostListen[])?  # inbound HTTP
---@field sql diluvium.HostSql?                # SQLite, host-side
---@field crypto diluvium.HostCrypto?          # random/hash/hmac/JWT, host-side
---@field fs diluvium.HostFs?                  # files within a granted scope
---@field exec (diluvium.HostExec|boolean)?    # subprocesses: LEAVING THE
---                                            # SANDBOX; true = defaults

---A listener, or an array of them. A v1 host binds at startup and never at
---runtime, so a deployment that will want several ports pre-binds the block
---here -- `listen = { {port=8080}, {port=8081} }` -- rather than binding one
---later. Up to 8. Ports must differ; queue names need not (all ports feeding
---one supervisor loop is the common case, and `conn` stays unique across
---them). A single block is still just `listen = { port = 8080 }`.
---@class diluvium.HostListen
---@field port integer                # required; 1..65535, unique per host
---@field bind string?                # IPv4 literal (default "127.0.0.1")
---@field queue string?               # requests land here, on the root
---                                   # (default "http_in"): {conn, method,
---                                   # path, body}
---@field reply_queue string?         # responses drain from here (default
---                                   # "http_out"): {conn, status, body,
---                                   # content_type?, headers?}
---@field max_body integer?           # refuse bigger bodies (default 65536)
---@field deadline_ms integer?        # per-connection; the host's own timeout
---                                   # logic (default 10000)
---@field max_conns integer?          # table bound (default 64)
---@field headers string[]?           # LOWERCASE allowlist of request headers
---                                   # forwarded to the guest as a `headers`
---                                   # map on each message; empty/omitted =
---                                   # none (default). Up to 8; repeats in a
---                                   # request join ", "; a value past the
---                                   # host's bound answers 431
---@field response_headers string[]?  # LOWERCASE allowlist of response
---                                   # headers a reply's `headers` map may
---                                   # set; empty/omitted = none (default).
---                                   # Up to 8. content-length, connection,
---                                   # transfer-encoding and content-type
---                                   # are the host's and refused here. A
---                                   # reply header not listed, carrying a
---                                   # control byte, or past the host's
---                                   # value bound is dropped whole, never
---                                   # truncated -- the response still
---                                   # answers without it

---The sql connector grants a *scope*: a directory the deployment's programs
---open databases within (`host.sql.open("name")` guest-side; `args.db` on
---the wire). Which database is the program's business, so it is not named
---here; a name that resolves outside the scope is denied. Every option but
---`scope` is omittable with a safe default, and nothing is preallocated --
---a database opens when a program first names it.
---@class diluvium.HostSql
---@field scope string                # the granted directory; required, must
---                                   # exist
---@field access ("read"|"readwrite")?  # the grant (default "read"); "read"
---                                   # opens files read-only and leaves
---                                   # sql/exec unwired
---@field create boolean?             # may a named database be created?
---                                   # needs access "readwrite", and
---                                   # defaults to it
---@field max_result_rows integer?    # per-QUERY result cap; past it the
---                                   # result REFUSES, never truncates
---                                   # (default 1024)

---The fs connector answers host:fs/read and host:fs/write with the same
---scope discipline as sql: the deployment grants a directory, the program
---names its file within it (`host.fs.read("notes/a.txt")`), and a path that
---names or resolves outside the scope is denied. Unlike a database name a
---path may descend into existing structure, but nothing here creates
---directories. Both directions refuse past `max_bytes` rather than
---truncate. `fs/write` is wired only under access "readwrite".
---@class diluvium.HostFs
---@field scope string                # the granted directory; required, must
---                                   # exist
---@field access ("read"|"readwrite")?  # default "read"; "read" leaves
---                                   # fs/write unwired
---@field max_bytes integer?          # cap on one read and one write
---                                   # (default 1048576)

---The exec connector answers host:exec/run: a subprocess, argv as a vector
---(no shell unless the program names one), stdin fed, stdout/stderr
---captured. GRANTING EXEC IS LEAVING THE SANDBOX -- the instruction budget
---cannot reach a child -- so the bounds here are the whole point. Note that
---THIS connector still answers synchronously, so a running child stalls
---every guest and the listener until it exits or hits the deadline. Build 8
---made deferral possible (a connector may take a call and answer later, as
---the plugin channel does) and deliberately did not convert `exec`, which
---is a behaviour change to a shipped connector and belongs in its own
---build. Bound it tight. `exec = true` wires it with the defaults.
---@class diluvium.HostExec
---@field max_timeout_ms integer?     # ceiling on a call's deadline; a child
---                                   # still running is killed
---                                   # (default 10000)
---@field max_output_bytes integer?   # per stream, and on stdin; past it the
---                                   # child is killed and the call refuses
---                                   # (default 1048576)

---The crypto connector answers host:crypto/random, /hash, /hmac, /jwt_sign,
---/jwt_verify and /turn_credential. The signing key never leaves the host:
---exactly one of key_file (the deployment shape), key_env, or key (inline,
---for dev) names it, and it must be at least 16 bytes. jwt_sign owns iat and
---exp -- a guest cannot forge a longer expiry -- and jwt_verify fixes the
---algorithm to HS256, so an "alg":"none" token is just an invalid one.
---@class diluvium.HostCrypto
---@field key string?                 # inline key (dev only); >= 16 bytes
---@field key_env string?             # name of an env var holding the key
---@field key_file string?            # path to a file holding the key
---@field default_ttl integer?        # jwt_sign ttl when a call omits it
---                                   # (seconds; default 3600)
---@field turn diluvium.HostCryptoTurn?  # TURN REST credentials; without it
---                                   # crypto/turn_credential is refused
---@field secrets table<string, diluvium.HostCryptoSecret>?  # named raw
---                                   # secrets crypto/hmac selects with
---                                   # args.key (webhook interop); at most 8

---One named raw secret. Raw because the peer (a webhook sender) computes
---the same MAC with the same bytes; still never handed to a guest.
---@class diluvium.HostCryptoSecret
---@field secret string?              # inline (dev only); >= 16 bytes
---@field secret_env string?          # name of an env var holding it
---@field secret_file string?         # path to a file holding it

---The TURN REST shared secret (coturn's use-auth-secret). Kept raw rather
---than derived -- the TURN server holds the same bytes and recomputes the
---MAC -- but it still never leaves the host: crypto/turn_credential hands a
---guest a finished credential, never the secret. The host owns the expiry
---the way jwt_sign owns exp.
---@class diluvium.HostCryptoTurn
---@field secret string?              # inline secret (dev only); >= 16 bytes
---@field secret_env string?          # name of an env var holding the secret
---@field secret_file string?         # path to a file holding the secret
---@field ttl integer?                # credential ttl when a call omits it
---                                   # (seconds; default 86400)
---@field uris string[]?              # TURN server URIs echoed verbatim in
---                                   # every credential (at most 8), e.g.
---                                   # "turn:turn.example.org:3478?transport=udp"
