/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_acos.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define one e_acos_one
#define pS0 e_acos_pS0
#define pS1 e_acos_pS1
#define pS2 e_acos_pS2
#define pS3 e_acos_pS3
#define pS4 e_acos_pS4
#define pS5 e_acos_pS5
#define pi e_acos_pi
#define pio2_hi e_acos_pio2_hi
#define pio2_lo e_acos_pio2_lo
#define qS1 e_acos_qS1
#define qS2 e_acos_qS2
#define qS3 e_acos_qS3
#define qS4 e_acos_qS4
