/* Generated by script/vendor_libm.sh. Do not edit. */
#undef huge
#undef one
#undef pS0
#undef pS1
#undef pS2
#undef pS3
#undef pS4
#undef pS5
#undef pio2_hi
#undef pio2_lo
#undef pio4_hi
#undef qS1
#undef qS2
#undef qS3
#undef qS4
