/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_asin.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define huge e_asin_huge
#define one e_asin_one
#define pS0 e_asin_pS0
#define pS1 e_asin_pS1
#define pS2 e_asin_pS2
#define pS3 e_asin_pS3
#define pS4 e_asin_pS4
#define pS5 e_asin_pS5
#define pio2_hi e_asin_pio2_hi
#define pio2_lo e_asin_pio2_lo
#define pio4_hi e_asin_pio4_hi
#define qS1 e_asin_qS1
#define qS2 e_asin_qS2
#define qS3 e_asin_qS3
#define qS4 e_asin_qS4
