/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_atan2.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define pi e_atan2_pi
#define pi_lo e_atan2_pi_lo
#define pi_o_2 e_atan2_pi_o_2
#define pi_o_4 e_atan2_pi_o_4
#define tiny e_atan2_tiny
#define zero e_atan2_zero
