/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_cosh.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define half e_cosh_half
#define huge e_cosh_huge
#define one e_cosh_one
