/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_exp.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define P1 e_exp_P1
#define P2 e_exp_P2
#define P3 e_exp_P3
#define P4 e_exp_P4
#define P5 e_exp_P5
#define halF e_exp_halF
#define huge e_exp_huge
#define invln2 e_exp_invln2
#define ln2HI e_exp_ln2HI
#define ln2LO e_exp_ln2LO
#define o_threshold e_exp_o_threshold
#define one e_exp_one
#define twom1000 e_exp_twom1000
#define u_threshold e_exp_u_threshold
