/* Generated by script/vendor_libm.sh. Do not edit. */
#undef P1
#undef P2
#undef P3
#undef P4
#undef P5
#undef halF
#undef huge
#undef invln2
#undef ln2HI
#undef ln2LO
#undef o_threshold
#undef one
#undef twom1000
#undef u_threshold
