/* Generated by script/vendor_libm.sh. Do not edit. */
#undef Lg1
#undef Lg2
#undef Lg3
#undef Lg4
#undef Lg5
#undef Lg6
#undef Lg7
#undef ivln2hi
#undef ivln2lo
#undef k_log1p
#undef two54
#undef zero
