/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_log10.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define Lg1 e_log10_Lg1
#define Lg2 e_log10_Lg2
#define Lg3 e_log10_Lg3
#define Lg4 e_log10_Lg4
#define Lg5 e_log10_Lg5
#define Lg6 e_log10_Lg6
#define Lg7 e_log10_Lg7
#define ivln10hi e_log10_ivln10hi
#define ivln10lo e_log10_ivln10lo
#define k_log1p e_log10_k_log1p
#define log10_2hi e_log10_log10_2hi
#define log10_2lo e_log10_log10_2lo
#define two54 e_log10_two54
#define zero e_log10_zero
