/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_log.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define Lg1 e_log_Lg1
#define Lg2 e_log_Lg2
#define Lg3 e_log_Lg3
#define Lg4 e_log_Lg4
#define Lg5 e_log_Lg5
#define Lg6 e_log_Lg6
#define Lg7 e_log_Lg7
#define ln2_hi e_log_ln2_hi
#define ln2_lo e_log_ln2_lo
#define two54 e_log_two54
#define zero e_log_zero
