/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_log2.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define Lg1 e_log2_Lg1
#define Lg2 e_log2_Lg2
#define Lg3 e_log2_Lg3
#define Lg4 e_log2_Lg4
#define Lg5 e_log2_Lg5
#define Lg6 e_log2_Lg6
#define Lg7 e_log2_Lg7
#define ivln2hi e_log2_ivln2hi
#define ivln2lo e_log2_ivln2lo
#define k_log1p e_log2_k_log1p
#define two54 e_log2_two54
#define zero e_log2_zero
