/* Generated by script/vendor_libm.sh. Do not edit. */
#undef Lg1
#undef Lg2
#undef Lg3
#undef Lg4
#undef Lg5
#undef Lg6
#undef Lg7
#undef ivln10hi
#undef ivln10lo
#undef k_log1p
#undef log10_2hi
#undef log10_2lo
#undef two54
#undef zero
