/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_pow.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define L1 e_pow_L1
#define L2 e_pow_L2
#define L3 e_pow_L3
#define L4 e_pow_L4
#define L5 e_pow_L5
#define L6 e_pow_L6
#define P1 e_pow_P1
#define P2 e_pow_P2
#define P3 e_pow_P3
#define P4 e_pow_P4
#define P5 e_pow_P5
#define bp e_pow_bp
#define cp e_pow_cp
#define cp_h e_pow_cp_h
#define cp_l e_pow_cp_l
#define dp_h e_pow_dp_h
#define dp_l e_pow_dp_l
#define huge e_pow_huge
#define ivln2 e_pow_ivln2
#define ivln2_h e_pow_ivln2_h
#define ivln2_l e_pow_ivln2_l
#define lg2 e_pow_lg2
#define lg2_h e_pow_lg2_h
#define lg2_l e_pow_lg2_l
#define one e_pow_one
#define ovt e_pow_ovt
#define tiny e_pow_tiny
#define two e_pow_two
#define two53 e_pow_two53
#define zero e_pow_zero
