/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_rem_pio2.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define invpio2 e_rem_pio2_invpio2
#define pio2_1 e_rem_pio2_pio2_1
#define pio2_1t e_rem_pio2_pio2_1t
#define pio2_2 e_rem_pio2_pio2_2
#define pio2_2t e_rem_pio2_pio2_2t
#define pio2_3 e_rem_pio2_pio2_3
#define pio2_3t e_rem_pio2_pio2_3t
#define two24 e_rem_pio2_two24
#define zero e_rem_pio2_zero
