/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes e_sinh.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define one e_sinh_one
#define shuge e_sinh_shuge
