/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes k_cos.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define C1 k_cos_C1
#define C2 k_cos_C2
#define C3 k_cos_C3
#define C4 k_cos_C4
#define C5 k_cos_C5
#define C6 k_cos_C6
#define one k_cos_one
