/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes k_exp.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define dv_frexp_exp k_exp_dv_frexp_exp
#define k k_exp_k
#define kln2 k_exp_kln2
