/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes k_rem_pio2.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define PIo2 k_rem_pio2_PIo2
#define init_jk k_rem_pio2_init_jk
#define ipio2 k_rem_pio2_ipio2
#define one k_rem_pio2_one
#define two24 k_rem_pio2_two24
#define twon24 k_rem_pio2_twon24
#define zero k_rem_pio2_zero
