/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes k_sin.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define S1 k_sin_S1
#define S2 k_sin_S2
#define S3 k_sin_S3
#define S4 k_sin_S4
#define S5 k_sin_S5
#define S6 k_sin_S6
#define half k_sin_half
