/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes s_atan.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define aT s_atan_aT
#define atanhi s_atan_atanhi
#define atanlo s_atan_atanlo
#define huge s_atan_huge
#define one s_atan_one
