/* Generated by script/vendor_libm.sh. Do not edit. */
#undef Q1
#undef Q2
#undef Q3
#undef Q4
#undef Q5
#undef huge
#undef invln2
#undef ln2_hi
#undef ln2_lo
#undef o_threshold
#undef one
#undef tiny
