/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes s_expm1.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define Q1 s_expm1_Q1
#define Q2 s_expm1_Q2
#define Q3 s_expm1_Q3
#define Q4 s_expm1_Q4
#define Q5 s_expm1_Q5
#define huge s_expm1_huge
#define invln2 s_expm1_invln2
#define ln2_hi s_expm1_ln2_hi
#define ln2_lo s_expm1_ln2_lo
#define o_threshold s_expm1_o_threshold
#define one s_expm1_one
#define tiny s_expm1_tiny
