/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes s_log1p.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define Lp1 s_log1p_Lp1
#define Lp2 s_log1p_Lp2
#define Lp3 s_log1p_Lp3
#define Lp4 s_log1p_Lp4
#define Lp5 s_log1p_Lp5
#define Lp6 s_log1p_Lp6
#define Lp7 s_log1p_Lp7
#define ln2_hi s_log1p_ln2_hi
#define ln2_lo s_log1p_ln2_lo
#define two54 s_log1p_two54
#define zero s_log1p_zero
