/* Generated by script/vendor_libm.sh. Do not edit. */
/* Scopes s_tanh.c's file-scope names for the one translation unit
   src/dlibm.c compiles every vendored source in. */
#define huge s_tanh_huge
#define one s_tanh_one
#define tiny s_tanh_tiny
#define two s_tanh_two
