/*
** dhostlib.c
** The 'host' guest library. See dhostlib.h for what it is and why.
**
** Implementation: an embedded Lua chunk. Everything the library does is
** orchestrate 'queue.*' -- declare the pair lazily, push a request, wait,
** correlate by token -- and Lua says that in a page. Keeping the body Lua is
** also the point of the design: when the language grows a real way to await
** a hostcall, this chunk's internals change and no call site does. The C
** below only compiles the chunk and hands its module table to
** 'luaL_requiref' (dlibs.c), which sets the 'host' global.
**
** State and snapshots. The chunk's state -- queue handles, the token
** counter, the stash of out-of-order replies -- lives in upvalues reachable
** only through the 'host' table, and the table is a *named permanent*
** (dsnap.c DS_MODULES): a snapshot stores the name, and a restore resolves
** it to the restored runtime's own fresh copy, state and all reset. That is
** correct because none of the state is program state: handles are runtime
** identity re-bound by name on first use, and a token only needs to be
** unique among calls outstanding *now*. A thread parked inside a call rides
** the snapshot as a content copy of these closures, exactly as the
** hand-rolled ask() it replaces did.
*/

#define dhostlib_c

#include "lprefix.h"

#include "lua.h"

#include "lauxlib.h"

#include "dhostlib.h"


static const char HOSTLIB_SRC[] =
  "local TIMEOUT_MS = 10000\n"
  "\n"
  "-- Tokens start high so the library's space is disjoint from the small\n"
  "-- integers every hand-rolled ask() uses: a program may mix raw pushes\n"
  "-- with these calls on the same queue pair (sequentially -- one reply\n"
  "-- queue cannot serve two concurrent consumers) and the tokens never\n"
  "-- collide.\n"
  "local TOK_BASE = 0x40000000\n"
  "\n"
  "local calls, replies      -- queue handles, bound lazily and by name\n"
  "local pending = {}        -- tok -> reply that arrived for another call\n"
  "local tok = TOK_BASE\n"
  "\n"
  "-- Look up before declaring: after a snapshot restore the queues exist\n"
  "-- (queue state rides in the root) while these upvalues start over, and a\n"
  "-- program mixing raw pushes with this library may have declared the pair\n"
  "-- itself. Hostcall.md's conventions: calls exported and rejecting when\n"
  "-- full, replies sized for the calls outstanding.\n"
  "local function ensure()\n"
  "  if not calls then\n"
  "    calls = queue.lookup(\"host/calls\") or queue.declare(\"host/calls\",\n"
  "              { capacity = 16, exported = true, on_full = \"reject\" })\n"
  "  end\n"
  "  if not replies then\n"
  "    replies = queue.lookup(\"host/replies\") or\n"
  "              queue.declare(\"host/replies\", { capacity = 16 })\n"
  "  end\n"
  "end\n"
  "\n"
  "-- One request, one reply. Replies arrive in whatever order the host\n"
  "-- answers, so a reply for a LATER token is stashed for the call it will\n"
  "-- answer; a reply for an earlier token can only be the late answer to a\n"
  "-- call that already timed out (calls are sequential), so it is dropped\n"
  "-- rather than retained forever -- as is a reply with no token, which\n"
  "-- answers nothing. Error levels: the public functions reach ask/try by\n"
  "-- proper tail call, so their frames are gone by the time anything here\n"
  "-- raises -- level 2 in ask/try and level 3 here already name the\n"
  "-- program's own call site.\n"
  "local function roundtrip(call, args, waitms)\n"
  "  ensure()\n"
  "  waitms = waitms or TIMEOUT_MS\n"
  "  tok = tok + 1\n"
  "  local t = tok\n"
  "  local sent, why = queue.push(calls, { tok = t, call = call, args = args })\n"
  "  if not sent then\n"
  "    error((\"host: could not send '%s': the call queue is %s\")\n"
  "          :format(call, tostring(why)), 3)\n"
  "  end\n"
  "  while true do\n"
  "    if pending[t] ~= nil then\n"
  "      local m = pending[t]\n"
  "      pending[t] = nil\n"
  "      return m\n"
  "    end\n"
  "    local _, m, st = queue.wait({ replies }, waitms)\n"
  "    if st == \"timeout\" then\n"
  "      error((\"host: no reply to '%s' within %d ms\")\n"
  "            :format(call, waitms), 3)\n"
  "    elseif st ~= \"ok\" then\n"
  "      error((\"host: no reply to '%s': the reply queue is %s\")\n"
  "            :format(call, st), 3)\n"
  "    end\n"
  "    if m.tok == t then\n"
  "      return m\n"
  "    elseif type(m.tok) == \"number\" and m.tok > t then\n"
  "      pending[m.tok] = m\n"
  "    end\n"
  "  end\n"
  "end\n"
  "\n"
  "-- The readable default: a non-ok status raises, with the connector's own\n"
  "-- sentence in the message. An unknown status is treated as an error, as\n"
  "-- Hostcall.md instructs.\n"
  "local function ask(call, args, waitms)\n"
  "  local m = roundtrip(call, args, waitms)\n"
  "  if m.status ~= \"ok\" then\n"
  "    error((\"host.%s: %s: %s\"):format((call:gsub(\"/\", \".\")),\n"
  "          tostring(m.status), tostring(m.detail)), 2)\n"
  "  end\n"
  "  return m.value\n"
  "end\n"
  "\n"
  "-- The pcall-friendly escape, for a program that expects a denial.\n"
  "local function try(call, args, waitms)\n"
  "  local m = roundtrip(call, args, waitms)\n"
  "  if m.status == \"ok\" then return m.value, \"ok\" end\n"
  "  return nil, tostring(m.status), m.detail\n"
  "end\n"
  "\n"
  "-- Parameters ride as a msgpack array, which is dense by definition: a nil\n"
  "-- hole cannot cross the wire, and SQL already has a spelling for NULL.\n"
  "local function params_of(what, ...)\n"
  "  local n = select(\"#\", ...)\n"
  "  if n == 0 then return nil end\n"
  "  local p = { ... }\n"
  "  for i = 1, n do\n"
  "    if p[i] == nil then\n"
  "      error((\"host.sql.%s: parameter %d is nil; an intentional NULL \"\n"
  "             .. \"is spelled host.sql.NULL (msgpack.null), or NULL in \"\n"
  "             .. \"the statement text\"):format(what, i), 3)\n"
  "    end\n"
  "  end\n"
  "  return p\n"
  "end\n"
  "\n"
  "-- The deployment grants a directory; the program names its database\n"
  "-- inside it, once, and works the returned handle. The handle's calls are\n"
  "-- dot-calls (db.exec, not db:exec) -- there is no self, only the name the\n"
  "-- closures carry -- and the statement check catches the colon mistake.\n"
  "local function statement_of(what, text)\n"
  "  if type(text) ~= \"string\" then\n"
  "    error((\"host.sql.%s: the statement must be a string (dot-call: \"\n"
  "           .. \"db.%s(...), not db:%s(...))\"):format(what, what, what), 3)\n"
  "  end\n"
  "  return text\n"
  "end\n"
  "local sql = {}\n"
  "-- The bindable NULL: a value, so a params list holding one is still a\n"
  "-- clean 1..n array (a nil would be a hole). The wire spells it msgpack\n"
  "-- nil and the connector binds SQL NULL; nil stays refused, because an\n"
  "-- accidental nil is still a bug worth catching.\n"
  "sql.NULL = msgpack.null\n"
  "function sql.open(name)\n"
  "  if type(name) ~= \"string\" or #name == 0 then\n"
  "    error(\"host.sql.open: name the database, a filename inside the \"\n"
  "          .. \"deployment's granted scope\", 2)\n"
  "  end\n"
  "  local db = {}\n"
  "  function db.exec(text, ...)\n"
  "    return ask(\"sql/exec\", { db = name, sql = statement_of(\"exec\", text),\n"
  "                             params = params_of(\"exec\", ...) })\n"
  "  end\n"
  "  function db.query(text, ...)\n"
  "    return ask(\"sql/query\", { db = name, sql = statement_of(\"query\", text),\n"
  "                              params = params_of(\"query\", ...) })\n"
  "  end\n"
  "  function db.try_exec(text, ...)\n"
  "    return try(\"sql/exec\",\n"
  "               { db = name, sql = statement_of(\"try_exec\", text),\n"
  "                 params = params_of(\"try_exec\", ...) })\n"
  "  end\n"
  "  function db.try_query(text, ...)\n"
  "    return try(\"sql/query\",\n"
  "               { db = name, sql = statement_of(\"try_query\", text),\n"
  "                 params = params_of(\"try_query\", ...) })\n"
  "  end\n"
  "  return db\n"
  "end\n"
  "\n"
  "local crypto = {}\n"
  "function crypto.hash(data)\n"
  "  return ask(\"crypto/hash\", { data = data })\n"
  "end\n"
  "-- opts.key selects a named raw secret (crypto.secrets) for webhook\n"
  "-- interop; opts.expect (hex) makes it a constant-time verification\n"
  "-- answering {valid=...} -- an answer, not an error, like jwt_verify.\n"
  "function crypto.hmac(data, opts)\n"
  "  return ask(\"crypto/hmac\", { data = data,\n"
  "                               key = opts and opts.key or nil,\n"
  "                               expect = opts and opts.expect or nil })\n"
  "end\n"
  "function crypto.random(nbytes)\n"
  "  return ask(\"crypto/random\", { bytes = nbytes })\n"
  "end\n"
  "function crypto.jwt_sign(claims, ttl)\n"
  "  return ask(\"crypto/jwt_sign\", { claims = claims, ttl = ttl })\n"
  "end\n"
  "-- An invalid token is an answer ({valid=false, reason}), not an error:\n"
  "-- the connector says so with status \"ok\", and this library agrees.\n"
  "function crypto.jwt_verify(token)\n"
  "  return ask(\"crypto/jwt_verify\", { token = token })\n"
  "end\n"
  "-- TURN REST credentials (coturn's use-auth-secret). The shared secret\n"
  "-- stays in the host, and the host owns the expiry the way jwt_sign\n"
  "-- owns exp: the call takes a ttl, never a timestamp.\n"
  "function crypto.turn_credential(user, ttl)\n"
  "  return ask(\"crypto/turn_credential\", { user = user, ttl = ttl })\n"
  "end\n"
  "\n"
  "local fs = {}\n"
  "function fs.read(path)\n"
  "  return ask(\"fs/read\", { path = path })\n"
  "end\n"
  "function fs.write(path, data, opts)\n"
  "  return ask(\"fs/write\", { path = path, data = data,\n"
  "                            append = opts and opts.append or nil })\n"
  "end\n"
  "function fs.try_read(path)\n"
  "  return try(\"fs/read\", { path = path })\n"
  "end\n"
  "function fs.try_write(path, data, opts)\n"
  "  return try(\"fs/write\", { path = path, data = data,\n"
  "                            append = opts and opts.append or nil })\n"
  "end\n"
  "\n"
  "-- A subprocess outlives every clock the VM owns, so the reply is waited\n"
  "-- on for the call's own deadline (or the host's ceiling at most) plus\n"
  "-- slack -- not the library's usual bound.\n"
  "local EXEC_CEILING_MS = 600000\n"
  "local execlib = {}\n"
  "function execlib.run(argv, opts)\n"
  "  return ask(\"exec/run\",\n"
  "             { argv = argv, stdin = opts and opts.stdin or nil,\n"
  "               timeout_ms = opts and opts.timeout_ms or nil,\n"
  "               cwd = opts and opts.cwd or nil },\n"
  "             ((opts and opts.timeout_ms) or EXEC_CEILING_MS) + 5000)\n"
  "end\n"
  "function execlib.try_run(argv, opts)\n"
  "  return try(\"exec/run\",\n"
  "             { argv = argv, stdin = opts and opts.stdin or nil,\n"
  "               timeout_ms = opts and opts.timeout_ms or nil,\n"
  "               cwd = opts and opts.cwd or nil },\n"
  "             ((opts and opts.timeout_ms) or EXEC_CEILING_MS) + 5000)\n"
  "end\n"
  "\n"
  "-- ==== the swarm half (build10) ====\n"
  "-- Capabilities.md section 8 applied to the lifecycle: the queue is the\n"
  "-- substrate, not the interface. The library owns the reserved names\n"
  "-- ('system/lifecycle' to ask, 'system/events' to hear -- Messaging.md\n"
  "-- 9.1/9.2), the op shapes, and the outcome wait, so a supervisor stops\n"
  "-- concatenating both by hand. Lifecycle requests are sequential through\n"
  "-- this library, the same discipline as the hostcall pair: outcomes\n"
  "-- carry no token, so order is the correlation.\n"
  "--\n"
  "-- What a handle is NOT: a channel. The swarm does not yet deliver\n"
  "-- endpoint references between instances (the recorded build7 cap4 gap),\n"
  "-- so there is no child:push here -- promising one would fake a\n"
  "-- capability the runtime does not have. When endpoint delivery lands,\n"
  "-- it lands on these handles without changing a call site.\n"
  "local lifeq, evq\n"
  "local children = {}       -- id -> handle, spawned via this library\n"
  "local evbuf, evhead, evtail = {}, 1, 0\n"
  "\n"
  "local function ensure_swarm()\n"
  "  if not lifeq then\n"
  "    lifeq = queue.lookup(\"system/lifecycle\") or\n"
  "            queue.declare(\"system/lifecycle\", { capacity = 8 })\n"
  "  end\n"
  "  if not evq then\n"
  "    evq = queue.lookup(\"system/events\") or\n"
  "          queue.declare(\"system/events\", { capacity = 16 })\n"
  "  end\n"
  "end\n"
  "\n"
  "-- A death notice updates the table; every event a waiter did not claim\n"
  "-- is buffered for host.events(), so waiting for a spawn outcome cannot\n"
  "-- eat an 'exited' that arrived first.\n"
  "local function note(ev)\n"
  "  local what = ev.event\n"
  "  if (what == \"exited\" or what == \"faulted\" or what == \"exceeded\")\n"
  "      and ev.id and children[ev.id] then\n"
  "    children[ev.id] = nil\n"
  "  end\n"
  "  evtail = evtail + 1\n"
  "  evbuf[evtail] = ev\n"
  "end\n"
  "\n"
  "-- Wait for the event 'claim' recognises, buffering the rest. The raise\n"
  "-- on timeout names the op, and level 3 names the program's call site.\n"
  "local function outcome(op, claim, waitms)\n"
  "  waitms = waitms or TIMEOUT_MS\n"
  "  while true do\n"
  "    local _, ev, st = queue.wait({ evq }, waitms)\n"
  "    if st == \"timeout\" then\n"
  "      error((\"host.%s: no lifecycle outcome within %d ms\")\n"
  "            :format(op, waitms), 3)\n"
  "    elseif st ~= \"ok\" then\n"
  "      error((\"host.%s: the events queue is %s\"):format(op, st), 3)\n"
  "    end\n"
  "    local verdict = claim(ev)\n"
  "    if verdict ~= nil then return verdict, ev end\n"
  "    note(ev)\n"
  "  end\n"
  "end\n"
  "\n"
  "-- host.spawn{code=..., caps=..., budget=..., wake_on_message=...,\n"
  "--            sealed=..., waitms=...} -> handle {id, kill}\n"
  "-- Raises on denial ('denied' names the refused capability or bound) and\n"
  "-- on a child that faulted before it was an instance.\n"
  "local function spawn(spec)\n"
  "  if type(spec) ~= \"table\" or type(spec.code) ~= \"string\" then\n"
  "    error(\"host.spawn: spec.code must be the child's chunk, a string\", 2)\n"
  "  end\n"
  "  ensure_swarm()\n"
  "  local sent, why = queue.push(lifeq, { op = \"spawn\", code = spec.code,\n"
  "    caps = spec.caps, budget = spec.budget,\n"
  "    wake_on_message = spec.wake_on_message, sealed = spec.sealed })\n"
  "  if not sent then\n"
  "    error((\"host.spawn: the lifecycle queue is %s\"):format(tostring(why)),\n"
  "          2)\n"
  "  end\n"
  "  local id = outcome(\"spawn\", function(ev)\n"
  "    if ev.event == \"spawned\" then return ev.id end\n"
  "    if ev.event == \"denied\" or\n"
  "       (ev.event == \"faulted\" and not children[ev.id]) then\n"
  "      error((\"host.spawn: %s: %s\"):format(ev.event,\n"
  "            tostring(ev.detail or ev.id)), 4)\n"
  "    end\n"
  "  end, spec.waitms)\n"
  "  local child = { id = id }\n"
  "  -- Dot-call, as db handles are: no self, only the id the closure holds.\n"
  "  function child.kill(waitms)\n"
  "    local ksent, kwhy = queue.push(lifeq, { op = \"kill\", id = id })\n"
  "    if not ksent then\n"
  "      error((\"host.kill: the lifecycle queue is %s\"):format(\n"
  "            tostring(kwhy)), 2)\n"
  "    end\n"
  "    return (outcome(\"kill\", function(ev)\n"
  "      if ev.id ~= id then return nil end\n"
  "      if ev.event == \"exited\" then note(ev) return true end\n"
  "      if ev.event == \"denied\" then\n"
  "        error((\"host.kill: %s\"):format(tostring(ev.detail)), 4)\n"
  "      end\n"
  "    end, waitms))\n"
  "  end\n"
  "  children[id] = child\n"
  "  return child\n"
  "end\n"
  "\n"
  "-- The children this library has spawned and not yet seen die. A fresh\n"
  "-- table each call: the ledger is the library's, not the caller's to\n"
  "-- mutate. After a snapshot restore this starts empty, like every other\n"
  "-- upvalue here -- the authoritative record of a supervision tree is the\n"
  "-- supervisor program's own state, which DOES ride the snapshot.\n"
  "local function children_of()\n"
  "  local out = {}\n"
  "  for id, child in pairs(children) do out[id] = child end\n"
  "  return out\n"
  "end\n"
  "\n"
  "-- The next lifecycle event: buffered first, then the queue. waitms of\n"
  "-- nil or 0 polls (a supervisor already parked on its own wait-set wants\n"
  "-- a drain, not a second place to sleep); a positive waitms parks here.\n"
  "-- Returns {event, id, detail?} or nil.\n"
  "local function events(waitms)\n"
  "  ensure_swarm()\n"
  "  if evhead <= evtail then\n"
  "    local ev = evbuf[evhead]\n"
  "    evbuf[evhead] = nil\n"
  "    evhead = evhead + 1\n"
  "    return ev\n"
  "  end\n"
  "  if waitms == nil or waitms == 0 then\n"
  "    local ev = queue.pop(evq)\n"
  "    if ev ~= nil then note(ev) return events(0) end\n"
  "    return nil\n"
  "  end\n"
  "  local _, ev, st = queue.wait({ evq }, waitms)\n"
  "  if st ~= \"ok\" then return nil end\n"
  "  note(ev)\n"
  "  return events(0)\n"
  "end\n"
  "\n"
  "return {\n"
  "  sql = sql,\n"
  "  crypto = crypto,\n"
  "  fs = fs,\n"
  "  exec = execlib,\n"
  "  spawn = spawn,\n"
  "  children = children_of,\n"
  "  events = events,\n"
  "  time = function() return ask(\"time\") end,\n"
  "  -- Milliseconds, same unit as time(), monotonic epoch: this host\n"
  "  -- process's own, so good for intervals within a run and reset by a\n"
  "  -- restart or a restore. Intervals here, records on time().\n"
  "  monotonic = function() return ask(\"time/monotonic\") end,\n"
  "  -- The generic escape, and the one a plugin capability arrives\n"
  "  -- through before any wrapper is generated for it. 'waitms' is\n"
  "  -- forwarded because the library's own default is tuned for a\n"
  "  -- connector answering out of local state, and a call that leaves\n"
  "  -- the machine is not that: a REST round trip inheriting 10s by\n"
  "  -- accident is a bug the call site cannot see.\n"
  "  call = function(name, args, waitms) return ask(name, args, waitms) end,\n"
  "  try = function(name, args, waitms) return try(name, args, waitms) end,\n"
  "  -- What this host can do, and what of it is yours. The two are\n"
  "  -- different questions and the answer keeps them apart: an entry the\n"
  "  -- program may not call is still an entry, with granted = false. That\n"
  "  -- is what lets a program tell 'this host cannot' from 'I may not',\n"
  "  -- which are different problems with different fixes.\n"
  "  capabilities = function() return ask(\"capabilities/list\") end,\n"
  "}\n"
;


LUAMOD_API int luaopen_dhostlib (lua_State *L) {
  if (luaL_loadbufferx(L, HOSTLIB_SRC, sizeof(HOSTLIB_SRC) - 1,
                       "=host", "t") != LUA_OK)
    return lua_error(L);
  lua_call(L, 0, 1);  /* the chunk returns the module table */
  return 1;
}
