/*
** dlibm.c
** The embedded libm, and the 'math' entries that route through it.
**
** See dlibm.h for why an embedded libm exists at all. This file is two
** things: the translation unit the vendored openlibm sources are
** compiled in, and the wrappers that put them behind 'math.exp' and its
** neighbours.
**
** Vendored, not written. src/libm/ holds openlibm's sources changed only
** by script/vendor_libm.sh -- four includes replaced, every exported
** symbol prefixed 'dv_', two export decorations dropped. src/libm/
** PROVENANCE names the upstream commit and LICENSE.md is upstream's,
** verbatim. No constant, branch or algorithm is altered, and the reason
** to keep it that way is the whole point of vendoring: what makes these
** functions trustworthy is that they are the ones a great many programs
** have already run.
**
** They are '#include'd rather than compiled separately for the same
** reason 'onelua.c' includes the rest of the runtime: one translation
** unit is one set of compiler flags, and doc/Plan-2026-09.md 3.5 is
** emphatic that the flags are the difference between a libm that agrees
** across targets and one that does not.
**
** ------------------------------------------------------------- surface --
**
** Entry points:
**   diluvium_libm_install   the only thing outside this file calls
**
** Configurable values:
**   DVLIBM_ROUTED           the 'math' entries that are replaced, and
**                           the only place that list appears
**
** Fan-out points:
**   dvlibm_routed           the name-to-wrapper table
**   the '#include' block    the vendored sources, in dependency order
*/

#define dlibm_c

#include "lprefix.h"

#include "lua.h"

#include "lauxlib.h"
#include "dlibm.h"

#if defined(DV_NUMERIC)

/*
** The vendored sources. Kernels first, so a reader meets the argument
** reduction before the functions that lean on it; the compiler does not
** care, since every one of these declares what it needs through
** dvlibm_private.h.
**
** The '.pre.h' and '.post.h' around each one are generated by
** script/vendor_libm.sh and do one job: rename that file's file-scope
** names for the length of its include, and put them back afterwards.
** Upstream compiles each of these separately, so eight of them declare
** their own 'static const double one' without ever meeting; here they
** all land in one translation unit. Scoping them with the preprocessor
** keeps the vendored sources exactly as upstream wrote them, which is
** the whole reason to vendor rather than to rewrite.
*/
#include "libm/k_sin.pre.h"
#include "libm/k_sin.c"
#include "libm/k_sin.post.h"

#include "libm/k_cos.pre.h"
#include "libm/k_cos.c"
#include "libm/k_cos.post.h"

#include "libm/k_tan.pre.h"
#include "libm/k_tan.c"
#include "libm/k_tan.post.h"

#include "libm/k_exp.pre.h"
#include "libm/k_exp.c"
#include "libm/k_exp.post.h"

#include "libm/k_rem_pio2.pre.h"
#include "libm/k_rem_pio2.c"
#include "libm/k_rem_pio2.post.h"

#include "libm/e_rem_pio2.pre.h"
#include "libm/e_rem_pio2.c"
#include "libm/e_rem_pio2.post.h"

#include "libm/e_exp.pre.h"
#include "libm/e_exp.c"
#include "libm/e_exp.post.h"

#include "libm/e_log.pre.h"
#include "libm/e_log.c"
#include "libm/e_log.post.h"

#include "libm/e_log2.pre.h"
#include "libm/e_log2.c"
#include "libm/e_log2.post.h"

#include "libm/e_log10.pre.h"
#include "libm/e_log10.c"
#include "libm/e_log10.post.h"

#include "libm/e_pow.pre.h"
#include "libm/e_pow.c"
#include "libm/e_pow.post.h"

#include "libm/s_sin.pre.h"
#include "libm/s_sin.c"
#include "libm/s_sin.post.h"

#include "libm/s_cos.pre.h"
#include "libm/s_cos.c"
#include "libm/s_cos.post.h"

#include "libm/s_tan.pre.h"
#include "libm/s_tan.c"
#include "libm/s_tan.post.h"

#include "libm/e_asin.pre.h"
#include "libm/e_asin.c"
#include "libm/e_asin.post.h"

#include "libm/e_acos.pre.h"
#include "libm/e_acos.c"
#include "libm/e_acos.post.h"

#include "libm/s_atan.pre.h"
#include "libm/s_atan.c"
#include "libm/s_atan.post.h"

#include "libm/e_atan2.pre.h"
#include "libm/e_atan2.c"
#include "libm/e_atan2.post.h"

#include "libm/e_sinh.pre.h"
#include "libm/e_sinh.c"
#include "libm/e_sinh.post.h"

#include "libm/e_cosh.pre.h"
#include "libm/e_cosh.c"
#include "libm/e_cosh.post.h"

#include "libm/s_tanh.pre.h"
#include "libm/s_tanh.c"
#include "libm/s_tanh.post.h"

#include "libm/s_expm1.pre.h"
#include "libm/s_expm1.c"
#include "libm/s_expm1.post.h"

#include "libm/s_log1p.pre.h"
#include "libm/s_log1p.c"
#include "libm/s_log1p.post.h"


/* ==================================================== the math entries == */

/*
** The wrappers.
**
** Each is 'lmathlib.c''s function with the platform call swapped for the
** vendored one, and nothing else: the same argument checking, the same
** number of results, the same behaviour on a bad argument. A program
** cannot tell which build it is running on except by the last bit of an
** answer, which is the point.
*/

static int dvlibm_exp (lua_State *L) {
  lua_pushnumber(L, dv_exp(luaL_checknumber(L, 1)));
  return 1;
}

/*
** 'math.log' takes an optional base, and lmathlib.c special-cases 2 and
** 10 so that log(8, 2) is exactly 3 rather than log(8)/log(2). Both
** special cases are kept -- dropping them would change an answer a
** program already relies on, on every target at once.
*/
static int dvlibm_log (lua_State *L) {
  lua_Number x = luaL_checknumber(L, 1);
  lua_Number res;
  if (lua_isnoneornil(L, 2))
    res = dv_log(x);
  else {
    lua_Number base = luaL_checknumber(L, 2);
    if (base == 2.0)
      res = dv_log2(x);
    else if (base == 10.0)
      res = dv_log10(x);
    else
      res = dv_log(x) / dv_log(base);
  }
  lua_pushnumber(L, res);
  return 1;
}

static int dvlibm_sin (lua_State *L) {
  lua_pushnumber(L, dv_sin(luaL_checknumber(L, 1)));
  return 1;
}

static int dvlibm_cos (lua_State *L) {
  lua_pushnumber(L, dv_cos(luaL_checknumber(L, 1)));
  return 1;
}

static int dvlibm_tan (lua_State *L) {
  lua_pushnumber(L, dv_tan(luaL_checknumber(L, 1)));
  return 1;
}

static int dvlibm_asin (lua_State *L) {
  lua_pushnumber(L, dv_asin(luaL_checknumber(L, 1)));
  return 1;
}

static int dvlibm_acos (lua_State *L) {
  lua_pushnumber(L, dv_acos(luaL_checknumber(L, 1)));
  return 1;
}

/* 'math.atan(y [, x])' is atan2 with x defaulting to 1, which is how
   lmathlib.c spells it and why there is no separate 'math.atan2' outside
   the compatibility block. */
static int dvlibm_atan (lua_State *L) {
  lua_Number y = luaL_checknumber(L, 1);
  lua_Number x = luaL_optnumber(L, 2, 1);
  lua_pushnumber(L, dv_atan2(y, x));
  return 1;
}

static int dvlibm_sinh (lua_State *L) {
  lua_pushnumber(L, dv_sinh(luaL_checknumber(L, 1)));
  return 1;
}

static int dvlibm_cosh (lua_State *L) {
  lua_pushnumber(L, dv_cosh(luaL_checknumber(L, 1)));
  return 1;
}

static int dvlibm_tanh (lua_State *L) {
  lua_pushnumber(L, dv_tanh(luaL_checknumber(L, 1)));
  return 1;
}

static int dvlibm_pow (lua_State *L) {
  lua_Number x = luaL_checknumber(L, 1);
  lua_Number y = luaL_checknumber(L, 2);
  lua_pushnumber(L, dv_pow(x, y));
  return 1;
}

static int dvlibm_log10 (lua_State *L) {
  lua_pushnumber(L, dv_log10(luaL_checknumber(L, 1)));
  return 1;
}

/*
** The list, and the only place it appears.
**
** 'atan2', 'cosh', 'sinh', 'tanh', 'pow' and 'log10' exist in 'math'
** only under LUA_COMPAT_MATHLIB. Replacing an absent entry would add it,
** so each of those is written only when it is already there -- a build
** without the compatibility layer keeps exactly the surface it had.
**
** 'sqrt', 'floor', 'ceil', 'abs', 'fmod', 'modf', 'ldexp' and 'frexp'
** are absent from this list on purpose: every one is exact, so the
** platform's already answers what this would.
*/
#define DVLIBM_ROUTED { \
  {"exp", dvlibm_exp}, \
  {"log", dvlibm_log}, \
  {"sin", dvlibm_sin}, \
  {"cos", dvlibm_cos}, \
  {"tan", dvlibm_tan}, \
  {"asin", dvlibm_asin}, \
  {"acos", dvlibm_acos}, \
  {"atan", dvlibm_atan}, \
  /* the compatibility set, replaced only where it exists */ \
  {"atan2", dvlibm_atan}, \
  {"sinh", dvlibm_sinh}, \
  {"cosh", dvlibm_cosh}, \
  {"tanh", dvlibm_tanh}, \
  {"pow", dvlibm_pow}, \
  {"log10", dvlibm_log10}, \
  {NULL, NULL} \
}

static const luaL_Reg dvlibm_routed[] = DVLIBM_ROUTED;

/* The first eight are unconditional; the rest replace an existing entry
   and are skipped when there is none. Counted rather than flagged per
   row, because the split is exactly lmathlib.c's own #if. */
#define DVLIBM_UNCONDITIONAL	8


LUA_API void diluvium_libm_install (lua_State *L, int idx) {
  const luaL_Reg *e;
  int n = 0;
  idx = lua_absindex(L, idx);
  luaL_checktype(L, idx, LUA_TTABLE);
  for (e = dvlibm_routed; e->name != NULL; e++, n++) {
    if (n >= DVLIBM_UNCONDITIONAL) {
      /* Only where 'math' already has it: adding 'math.pow' to a build
         that does not have it would be a surface change hiding inside a
         precision one. */
      int had = (lua_getfield(L, idx, e->name) != LUA_TNIL);
      lua_pop(L, 1);
      if (!had) continue;
    }
    lua_pushcfunction(L, e->func);
    lua_setfield(L, idx, e->name);
  }
}

#else  /* !DV_NUMERIC */

/*
** Without the feature 'math' keeps the platform's functions, which is
** what makes such a build byte-identical to one from before this file
** existed. A no-op rather than an absent symbol, so 'dlibs.c' needs no
** '#if' of its own.
*/
LUA_API void diluvium_libm_install (lua_State *L, int idx) {
  (void)L; (void)idx;
}

#endif  /* DV_NUMERIC */
