// Reading the release mirror.
//
// /release is generated by util/scripts/release_mirror.py in launchkit, from
// changelog.json in the diluvium tree. releases.json is its index; latest/ is
// a symlink to whichever tag the changelog marks. The page reads the mirror
// rather than the GitHub API so it costs no rate limit and keeps working when
// GitHub does not.

export const BASE = RELEASE_BASE;   // injected by webpack's DefinePlugin

export const KERNEL_URL = `${BASE}/latest/libdiluvium_wasi.wasm`;

// The downloadable interpreter, per platform. Names come from the release
// workflow; the mirror carries them verbatim.
const TARGETS = [
  { id: 'linux-x86_64',  label: 'Linux · x86-64',        asset: 'diluvium_linux_static_x86_64' },
  { id: 'linux-aarch64', label: 'Linux · ARM64',         asset: 'diluvium_linux_static_aarch64' },
  { id: 'linux-armv7l',  label: 'Linux · ARMv7',         asset: 'diluvium_linux_static_armv7l' },
  { id: 'darwin-arm64',  label: 'macOS · Apple silicon', asset: 'diluvium_darwin_arm64' },
  { id: 'darwin-x86_64', label: 'macOS · Intel',         asset: 'diluvium_darwin_x86_64' },
  { id: 'windows-x86_64', label: 'Windows · x86-64',     asset: 'diluvium_windows_x86_64.exe' },
];

export function targets() { return TARGETS; }

// Best-effort, and only used to decide which download to show first. Every
// target stays listed whatever this guesses, and the install script does the
// real detection on the machine that will run the binary -- which is the only
// place it can be done correctly.
export function guessTarget() {
  const ua = navigator.userAgent;
  const platform = navigator.userAgentData?.platform || navigator.platform || '';
  const arm = /arm|aarch64/i.test(ua);

  if (/Win/i.test(platform)) return 'windows-x86_64';
  if (/Mac/i.test(platform) || /Mac/i.test(ua)) {
    // Safari reports Intel on Apple silicon and there is no reliable way
    // around it from script. Apple silicon is the likelier machine now, so
    // that is the guess; the Intel build is one click away in the list.
    return 'darwin-arm64';
  }
  if (/Linux|X11|Android/i.test(platform) || /Linux/i.test(ua)) {
    return arm ? 'linux-aarch64' : 'linux-x86_64';
  }
  return 'linux-x86_64';
}

export async function loadIndex() {
  const r = await fetch(`${BASE}/releases.json`, { cache: 'no-cache' });
  if (!r.ok) throw new Error(`${r.status} fetching releases.json`);
  const doc = await r.json();
  const latest = doc.releases?.find((x) => x.tag === doc.latest) || doc.releases?.[0];
  return { doc, latest };
}

export function assetUrl(tag, asset) {
  return `${BASE}/${encodeURIComponent(tag)}/${asset}`;
}

export function notesUrl(rel) {
  return rel?.notes ? `${BASE}/${encodeURIComponent(rel.tag)}/${rel.notes}` : null;
}
